### ISSUE TITLE
Cannot get this repo to work because of dependency issues. 

### ISSUE THREAD

**Issue by gardncl** [bfil/scalescrape#1]
I currently have this post on stack overflow:

https://stackoverflow.com/questions/48363010/scala-claims-i-am-using-different-versions-of-akka

And these two commits that when trying to run main locally they fail:
[Just this repo and akka actors](https://github.com/gardncl/scala-sputnik-scraper/tree/e3638b5cdbc24f6a1bcf03d540dae184232b05ca)

[This repo plus I also overwrite akka streams as told to do on stack overflow](https://github.com/gardncl/scala-sputnik-scraper/commit/8d1b94607c08e35a6a0d73e0aecae9f43fda945c)

These are the conflicts I get:

```shell
~ sbt evicted
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/gardncl/.sbt/1.0/plugins
[info] Loading project definition from /Users/gardncl/dev/dev-projects/scala/sputnik-scraper/project
[info] Loading settings from build.sbt ...
[info] Set current project to sputnik-scraper (in build file:/Users/gardncl/dev/dev-projects/scala/sputnik-scraper/)
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* com.typesafe.akka:akka-stream_2.12:2.5.8 is selected over 2.4.16
[warn] 	    +- sputnik-scraper:sputnik-scraper_2.12:0.1           (depends on 2.4.16)
[warn] 	    +- com.typesafe.akka:akka-http-core_2.12:10.0.1       (depends on 2.4.16)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Here are other depedency conflicts that were resolved:
[info] 	* com.typesafe.akka:akka-http_2.12:10.0.1 is selected over 10.0.0
[info] 	    +- io.bfil:scalescrape_2.12:0.4.0                     (depends on 10.0.1)
[info] 	    +- de.heikoseeberger:akka-http-json4s_2.12:1.11.0     (depends on 10.0.0)
[info] 	* com.typesafe:config:1.3.2 is selected over 1.2.0
[info] 	    +- com.typesafe:ssl-config-core_2.12:0.2.2            (depends on 1.2.0)
[info] 	    +- com.typesafe.akka:akka-actor_2.12:2.5.8 ()         (depends on 1.2.0)
[success] Total time: 3 s, completed Jan 21, 2018 8:31:45 AM
```

This repo seems to come with incompatible types?

**Comment by gardncl** [comment]
Perhaps I should be more clear. This _should_ be fine, but running a very basic example doesn't actually work:

https://pastebin.com/GKnXGTvu

**Comment by bfil** [comment]
@gardncl the issue seems to be caused by `akka-http` which seem to require to explicitly set the dependency on `akka-stream` `2.5.x` if a project uses `akka` `2.5.x`, see this comment: https://github.com/akka/akka-http/issues/1101#issuecomment-299923102

A quick fix would be to add the `akka-stream` dependency explicitly to your project.

I'm also working pushing a new version of Scalescrape (`0.4.1`) which will add the explicit dependency on `akka-stream` `2.5.8` and also bump up a couple of other libraries depending on older versions of `akka`. The new version should be available on Maven central in the next couple of hours but if you need it sooner you can temporarily my Bintray resolver (as indicated in the README).

This madness should be sorted out starting from Akka HTTP version `10.1.0` which will mark the `akka-stream` dependency as `provided`, as indicated here: https://github.com/akka/akka-http/blob/58784594d4ab5f9da59920f91db057e4138befd0/docs/src/main/paradox/compatibility-guidelines.md

This should fix your issue, I've tried to run your repo with the latest `akka-stream` and it seemed to be running so I'm closing this. Please let me know if it worked on your side as well, thanks!

**Comment by gardncl** [comment]
Thanks! I moved onto a different scraping library, so no need for me to verify this one.
